name: C/C++ CI

on: [push, pull_request]

jobs:
  test-amd64:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Build with CMake
        run: |
          mkdir -p build
          cd build
          cmake ..
          make
      - name: Run tinymembench
        run: ./build/tinymembench

  test-armhf:

    runs-on: ubuntu-18.04
    
    env:
      TOOLCHAIN_PACKAGE: crossbuild-essential-armhf
      LIBC_PACKAGE: libc6-armhf-cross
      CROSS_C_COMPILER: "/usr/bin/arm-linux-gnueabihf-gcc"

    steps:
      - name: Update package lists
        run: sudo apt-get update
      - name: Install QemuUserEmulation
        run: sudo apt-get install -y --no-install-recommends qemu binfmt-support qemu-user-static
      - name: Install toolchain
        run: sudo apt-get install -y --no-install-recommends $TOOLCHAIN_PACKAGE $LIBC_PACKAGE
      - uses: actions/checkout@v1
      - name: Build with CMake
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_C_COMPILER=$CROSS_C_COMPILER ..
          make
      - name: Run tinymembench
        run: ./build/tinymembench
