name: C/C++ CI

on: [push, pull_request]

jobs:
  test-amd64:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Build with CMake
      run: |
        mkdir -p build
        cd build
        cmake ..
        make
    - name: Run tinymembench
      run: ./build/tinymembench

  test-armhf:

    runs-on: ubuntu-18.04

    steps:
    - name: Install QemuUserEmulation
      run: sudo apt-get install -y --no-install-recommends qemu binfmt-support qemu-user-static
    - name: Install crossbuild-essential-armhf
      run: sudo apt-get install -y --no-install-recommends crossbuild-essential-armhf
    - uses: actions/checkout@v1
    - name: Build with CMake
      run: |
        mkdir -p build
        cd build
        cmake -DCMAKE_C_COMPILER=arm-linux-gnueabihf-gcc ..
        make
    - name: Run tinymembench
      run: ./build/tinymembench
