name: C/C++ CI

on:
  push:
    branches:
    - master
    - devel
  pull_request:
    branches:
    - master
    - devel

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: Build with CMake
      run: |
        mkdir -p build
        cd build
        cmake ..
        make
    - name: Run tinymembench
      run: ./build/tinymembench
